Ticket 190 upgrade to django 3
VNG-Realisatie/vng-api-common pull request #191
Opened 2022-02-21 21:57 UTC by ahmadpoorgholam

2022-02-22 09:39 UTC, ahmadpoorgholam commented
I will add "isort", "docs" to the tox command soon

2022-02-22 09:42 UTC, sergei-maertens requested changes
There are a lot of warnings too when running tests with Django 3.2 - can you resolve those? They will make upgrading to Django 4.x at some point easier.

2022-02-22 09:42 UTC, sergei-maertens commented on .github/workflows/ci.yml
> +        django: [ '2.2', '3.2' ]
good improvement, but we lost tox envs `isort` and `docs` here.

can you:

*  add a separate docs workflow job like in Open Zaak: https://github.com/open-zaak/open-zaak/blob/main/.github/workflows/ci.yml#L180 and 
* add a code_quality.yml workflow that runs at least isort, you can use https://github.com/open-zaak/open-zaak/blob/main/.github/workflows/code_quality.yml for inspiration

2022-02-22 09:42 UTC, sergei-maertens commented on .github/workflows/ci.yml
> +        django: [ '2.2', '3.2' ]
Additionally, please update the `name` of the job which now still references the `${{ matrix.env }}` which is no longer defined.

2022-02-22 09:42 UTC, sergei-maertens commented on setup.cfg
> +    django < 4.0
I'd still require a minimum version of Django though

```suggestion
    django>=2.2,< 4.0
```

2022-02-22 09:45 UTC, sergei-maertens requested changes
I'm also missing the required import/code change that breaks cmis-adapter.

The vng-api-common test-suite is not extensive enough and that codepath is not covered, clearly.

2022-03-09 17:04 UTC, sergei-maertens commented
Doing this in #193

2022-03-09 17:04 UTC, closed without merging